name: CMake

on:
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Cpplint check
      run: |
        pip install cpplint
        cpplint --extensions=c src/*
      
    - name: Cppcheck check
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --enable=all --suppress=missingInclude src/
      
    - name: Cmake build
      run: |
          sudo apt-get install -y gcovr
          mkdir build && cd build
          sudo apt-get install -y libgtest-dev
          cmake ..
        
    - name: Build unit_tests
      run: |
        cd build
        make unit_test
      
    - name: Unit testing
      run: |
        .build/unit_test
        
    - name: Gcovr test
      run: gcovr -r . --html -o example-html.html
