name: CMake

on:
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Cpplint check
      run: |
        pip install cpplint
        cpplint --extensions=c src/*
      
    - name: Cppcheck check
      run: |
        sudo apt-get install -y cppcheck
        cppcheck --enable=all --suppress=missingInclude src/
      
    - name: Cmake build
      run: |
          sudo apt-get install -y gcovr
          mkdir build && cd build
          sudo apt-get install -y libgtest-dev
          cmake ..
        
    - name: Build unit_tests
      run: |
        cd build
        make unit_test
      
    - name: Unit testing
      run: |
        cd build
        ./unit_test
        
    - name: Gcovr test
      run: |
        mkdir coverage-report && cd coverage-report
        gcovr -r ../ --html --html-details -o coverage_report.html
        
    - name: Make gcovr artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Gcovr test
        path: coverage-report/
        
    - name: Valgrind test
      run: |
        sudo apt-get install -y valgrind
        mkdir valgrind-report
        valgrind --tool=memcheck --leak-check=yes --log-file=valgrind-report/valgrind_report.txt ./build/unit_test

    - name: Make valgrind artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Valgrind test
        path: valgrind-report/
